create table public.notifications (
  id bigserial not null,
  uid text null,
  recipient_id bigint null,
  content text null,
  read boolean null default false,
  sender_id bigint null,
  referenced_bucket_id bigint null,
  referenced_post_id bigint null,
  type bigint null,
  creator text null,
  created_by bigint null,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  sender_email text null,
  reciever_email text null,
  type_text text null,
  referenced_bucket_uid text null,
  referenced_post_uid text null,
  constraint notifications_pkey primary key (id),
  constraint notifications_recipient_id_fkey foreign KEY (recipient_id) references users (id) on delete CASCADE,
  constraint notifications_created_by_fkey foreign KEY (created_by) references users (id) on delete CASCADE,
  constraint notifications_referenced_post_id_fkey foreign KEY (referenced_post_id) references posts (id) on delete CASCADE,
  constraint notifications_sender_id_fkey foreign KEY (sender_id) references users (id) on delete CASCADE,
  constraint notifications_type_fkey foreign KEY (type) references type_of_notifications (id),
  constraint notifications_referenced_bucket_id_fkey foreign KEY (referenced_bucket_id) references buckets (id) on delete CASCADE
) TABLESPACE pg_default;