create table public.story_board_items (
  id bigserial not null,
  uid text null,
  answer text null,
  random text null,
  link boolean null default false,
  picture_url text null,
  colour bigint null,
  related_bucket_id bigint null,
  question bigint null,
  creator text null,
  created_by bigint null,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  colour_text text null,
  question_text text null,
  related_bucket_uid text null,
  sort_factor integer null,
  constraint story_board_items_pkey primary key (id),
  constraint story_board_items_colour_fkey foreign KEY (colour) references colours (id),
  constraint story_board_items_created_by_fkey foreign KEY (created_by) references users (id) on delete CASCADE,
  constraint story_board_items_question_fkey foreign KEY (question) references story_board_qs (id),
  constraint story_board_items_related_bucket_id_fkey foreign KEY (related_bucket_id) references buckets (id) on delete CASCADE
) TABLESPACE pg_default;